---
- name: Ensure /etc/group with right permissions
  hosts: "{{ NODES }}"
  gather_facts: false
  become: true
  tasks:
    - name: Ensure /etc/group permissions
      ansible.builtin.file:
        path: /etc/group
        owner: root
        group: root
        mode: '644'
