---
- hosts: "{{ NODES }}"
  gather_facts: false
  become: true
  tasks:
    - name: Ensure /etc/passwd permissions
      ansible.builtin.file:
        path: /etc/passwd
        owner: root
        group: root
        mode: '644'
