---
- name: Update /etc/login.defs
  hosts: "{{ NODES }}"
  #gather_facts: false
  become: true
  vars:
    bss_motd_file: "Welcome to Production Server.\n(This is managed by Ansible)\n"
  tasks:
    - name: Set Password Expiration Days
      lineinfile:
        dest: '/etc/login.defs'
        regexp: "PASS_MAX_DAYS"
        line: "PASS_MAX_DAYS 90"
        state: present

    - name: Set Password Expiration Days
      lineinfile:
        dest: '/etc/login.defs'
        regexp: "PASS_MIN_DAYS"
        line: "PASS_MIN_DAYS 7"
        state: present

    - name: Disable System Accounts
      command: /usr/sbin/usermod -s /usr/sbin/nologin libuuid
      when: ansible_distribution == "Ubuntu"

    - name: Set Default umask for Users
      lineinfile:
        dest: '/etc/login.defs'
        regexp: "UMASK"
        line: "UMASK 022"
        state: present
