---
- name: Ensure /etc/shadow with right permissions
  hosts: "{{ NODES }}"
  gather_facts: false
  become: true
  tasks:
    - name: Ensure /etc/shadow permissions
      ansible.builtin.file:
        path: /etc/shadow
        owner: root
        group: root
        mode: '000'
